export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS';
export const SEARCH_POKEMON_STARTED = 'SEARCH_POKEMON_STARTED';
export const SEARCH_POKEMON_FAILED = 'SEARCH_POKEMON_FAILED';
export const SEARCH_POKEMON_NOT_FOUND = 'SEARCH_POKEMON_NOT_FOUND';
